[package]
name = "msp430_blinky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.msp430fr2x5x-hal]
path = "../msp430fr2x5x-hal"